# Generated by Django 5.2.12 on 2026-04-07 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_appuser_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='YooMoneyNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='ID операции')),
                ('label', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Метка')),
                ('sha1_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA1')),
                ('is_valid', models.BooleanField(default=False, verbose_name='Валидно')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Лог уведомления ЮMoney',
                'verbose_name_plural': 'Логи уведомлений ЮMoney',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Метка платежа')),
                ('plan_key', models.CharField(choices=[('30', '1 месяц'), ('90', '3 месяца'), ('365', '12 месяцев')], max_length=10, verbose_name='Код тарифа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('days', models.PositiveIntegerField(verbose_name='Дней доступа')),
                ('payment_method', models.CharField(default='yoomoney', max_length=20, verbose_name='Метод оплаты')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('operation_id', models.CharField(blank=True, default='', max_length=100, verbose_name='ID операции ЮMoney')),
                ('payer', models.CharField(blank=True, default='', max_length=64, verbose_name='Плательщик')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оплаченная сумма')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoices', to='users.appuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Счёт на оплату',
                'verbose_name_plural': 'Счета на оплату',
                'ordering': ['-created_at'],
            },
        ),
    ]
