# Generated by Django 5.2.12 on 2026-04-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(blank=True, choices=[('BY', 'Беларусь'), ('RU', 'Россия')], max_length=2, verbose_name='Страна'),
        ),
    ]
