# Generated by Django 5.2.12 on 2026-04-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_appuser_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='country',
        ),
    ]
