# Generated by Django 5.2.12 on 2026-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_appuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_chat_setup_mode',
            field=models.BooleanField(default=False, verbose_name='Режим настройки чатов'),
        ),
    ]
