# Generated by Django 5.2.12 on 2026-04-03 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appuser_is_chat_setup_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_chat_setup_mode',
        ),
    ]
