# Generated by Django 5.2.12 on 2026-04-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_appuser_is_chat_setup_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_trial_used',
            field=models.BooleanField(default=False, verbose_name='Пробный период использован'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подписка активна до'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='trial_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец пробного периода'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало пробного периода'),
        ),
    ]
