# Generated by Django 5.2.12 on 2026-04-06 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_appuser_is_trial_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stars', 'Telegram Stars'), ('yoomoney', 'ЮMoney'), ('admin', 'Выдано админом'), ('', 'Не указано')], default='', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
