# Generated by Django 5.2.12 on 2026-04-01 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram Chat ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username/ссылка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Чат для мониторинга',
                'verbose_name_plural': 'Чаты для мониторинга',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, verbose_name='Ключевое слово')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='users.appuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ключевое слово',
                'verbose_name_plural': 'Ключевые слова',
                'ordering': ['phrase'],
            },
        ),
        migrations.CreateModel(
            name='MatchedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField(verbose_name='ID сообщения')),
                ('message_text', models.TextField(verbose_name='Текст сообщения')),
                ('matched_keyword', models.CharField(max_length=255, verbose_name='Найденное слово')),
                ('message_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хэш')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser', verbose_name='Пользователь')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredchat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Найденное сообщение',
                'verbose_name_plural': 'Найденные сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserChatSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.monitoredchat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на чат',
                'verbose_name_plural': 'Подписки на чаты',
                'unique_together': {('user', 'chat')},
            },
        ),
    ]
