# Generated by Django 5.2.12 on 2026-04-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredchat',
            options={'ordering': ['title', 'id'], 'verbose_name': 'Чат для мониторинга', 'verbose_name_plural': 'Чаты для мониторинга'},
        ),
        migrations.AddField(
            model_name='monitoredchat',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Что ввели'),
        ),
        migrations.AlterField(
            model_name='monitoredchat',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AlterField(
            model_name='monitoredchat',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
    ]
