# Generated by Django 5.2.12 on 2026-04-02 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_monitoredchat_options_monitoredchat_input_name_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=255, verbose_name='Стоп-слово')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_words', to='users.appuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стоп-слово',
                'verbose_name_plural': 'Стоп-слова',
                'ordering': ['phrase'],
            },
        ),
    ]
