# Generated by Django 5.2.12 on 2026-04-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_stopword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchedmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Техническое совпадение', 'verbose_name_plural': 'Технические совпадения'},
        ),
        migrations.RemoveField(
            model_name='matchedmessage',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='matchedmessage',
            name='matched_keyword',
        ),
        migrations.RemoveField(
            model_name='matchedmessage',
            name='message_text',
        ),
        migrations.RemoveField(
            model_name='matchedmessage',
            name='telegram_message_id',
        ),
    ]
