# Generated by Django 5.2.12 on 2026-04-02 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_matchedmessage_options_and_more'),
        ('users', '0002_appuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredchat',
            name='country',
            field=models.CharField(choices=[('BY', 'Беларусь'), ('RU', 'Россия')], default=1, max_length=2, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('BY', 'Беларусь'), ('RU', 'Россия')], max_length=2, verbose_name='Страна')),
                ('chat_input', models.CharField(max_length=255, verbose_name='Имя чата или ссылка')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.appuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на добавление чата',
                'verbose_name_plural': 'Заявки на добавление чатов',
                'ordering': ['-created_at'],
            },
        ),
    ]
