# Generated by Django 5.2.12 on 2026-04-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_monitoredchat_country_chatrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredchat',
            options={'ordering': ['country', 'title', 'id'], 'verbose_name': 'Чат для мониторинга', 'verbose_name_plural': 'Чаты для мониторинга'},
        ),
    ]
