# Generated by Django 5.2.12 on 2026-04-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_monitoredchat_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrequest',
            name='country',
            field=models.CharField(choices=[('BY', 'Беларусь'), ('RU', 'Россия'), ('OTHER', 'Другая страна')], max_length=10, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='monitoredchat',
            name='country',
            field=models.CharField(choices=[('BY', 'Беларусь'), ('RU', 'Россия'), ('OTHER', 'Другая страна')], max_length=10, verbose_name='Страна'),
        ),
    ]
